#!/bin/bash
# Démo bonus : CGI Bash (type .sh)
# Démontre que le serveur gère plusieurs types CGI (.py ET .sh)

SESSION_ID="${SESSION_ID:-inconnue}"
SESSION_COUNT="${SESSION_COUNT:-0}"

echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html><head><title>CGI Bash Demo</title>"
echo "<style>body{font-family:monospace;padding:20px;}"
echo "table{border-collapse:collapse;} td,th{border:1px solid #ccc;padding:8px;}</style>"
echo "</head><body>"
echo "<h1>Demo Bonus — CGI Bash (.sh)</h1>"
echo "<p>Ce script prouve que le serveur gère plusieurs types CGI (.py, .sh).</p>"
echo "<table>"
echo "  <tr><th>Variable</th><th>Valeur</th></tr>"
echo "  <tr><td>SESSION_ID</td><td>${SESSION_ID}</td></tr>"
echo "  <tr><td>SESSION_COUNT</td><td>${SESSION_COUNT}</td></tr>"
echo "  <tr><td>REQUEST_METHOD</td><td>${REQUEST_METHOD}</td></tr>"
echo "  <tr><td>QUERY_STRING</td><td>${QUERY_STRING}</td></tr>"
echo "  <tr><td>SERVER_PORT</td><td>${SERVER_PORT}</td></tr>"
echo "  <tr><td>Date</td><td>$(date)</td></tr>"
echo "</table>"
echo "<p>"
echo "  <a href='/tests/hello.py'>CGI Python</a> |"
echo "  <a href='/tests/session_cgi.py'>Session CGI</a> |"
echo "  <a href='/session'>Page session</a> |"
echo "  <a href='/'>Accueil</a>"
echo "</p>"
echo "</body></html>"
